/*
 * bench.c - see bench.h. No process or display code here (unit-tested).
 */
#include "bench.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "hutil.h"

/* ---------------------------------------------------------------- plans */

static struct bench_config *config_for(struct bench_plan *p, const char *id)
{
	for (int i = 0; i < p->n; i++)
		if (!strcmp(p->c[i].id, id))
			return &p->c[i];
	if (p->n >= BENCH_MAX_CONFIGS)
		return NULL;
	memset(&p->c[p->n], 0, sizeof(p->c[0]));
	hstrlcpy(p->c[p->n].id, id, sizeof(p->c[0].id));
	return &p->c[p->n++];
}

static void run_field(struct bench_plan *p, const char *k, const char *v)
{
	static const struct { const char *key; size_t off, size; } map[] = {
#define F(name) { #name, offsetof(struct bench_plan, name), sizeof(((struct bench_plan *)0)->name) }
		F(game), F(system), F(rom_stem), F(core_id), F(core_path), F(state), F(state_core),
		F(results), F(auto_state), F(date),
#undef F
	};

	for (size_t i = 0; i < sizeof(map) / sizeof(map[0]); i++)
		if (!strcasecmp(k, map[i].key))
			hstrlcpy((char *)p + map[i].off, v, map[i].size);
}

int bench_plan_parse(const struct ini *ini, const char *default_core, struct bench_plan *p)
{
	memset(p, 0, sizeof(*p));
	p->seconds = 25;
	p->warmup = 5;
	for (int i = 0; i < ini->n; i++) {
		const struct ini_entry *e = &ini->e[i];
		struct bench_config *c;

		if (!e->section[0])
			continue;
		if (!strcasecmp(e->section, "bench")) {
			if (!strcasecmp(e->key, "seconds"))
				p->seconds = atoi(e->value);
			else if (!strcasecmp(e->key, "warmup"))
				p->warmup = atoi(e->value);
			continue;
		}
		if (!strcasecmp(e->section, "run")) {
			run_field(p, e->key, e->value);
			continue;
		}
		c = config_for(p, e->section);
		if (!c)
			continue;
		if (!strcasecmp(e->key, "label"))
			hstrlcpy(c->label, e->value, sizeof(c->label));
		else if (!strcasecmp(e->key, "core"))
			hstrlcpy(c->core, e->value, sizeof(c->core));
		else if (c->nkv < BENCH_MAX_KEYS) {
			hstrlcpy(c->kv[c->nkv].key, e->key, sizeof(c->kv[0].key));
			hstrlcpy(c->kv[c->nkv].value, e->value, sizeof(c->kv[0].value));
			c->nkv++;
		}
	}
	if (p->seconds < 1)
		p->seconds = 1;
	if (p->warmup < 0)
		p->warmup = 0;
	for (int i = 0; i < p->n; i++) {
		if (!p->c[i].core[0])
			hstrlcpy(p->c[i].core, default_core ? default_core : p->core_id, sizeof(p->c[i].core));
		if (!p->c[i].label[0])
			hstrlcpy(p->c[i].label, p->c[i].id, sizeof(p->c[i].label));
	}
	return p->n > 0 ? 0 : -EINVAL;
}

int bench_plan_load(const char *path, const char *default_core, struct bench_plan *p)
{
	struct ini ini = { 0 };
	int r = ini_load(&ini, path);

	if (r == 0)
		r = bench_plan_parse(&ini, default_core, p);
	else
		memset(p, 0, sizeof(*p));
	ini_free(&ini);
	return r;
}

struct sbuf {
	char *b;
	size_t n, len;
};

static void sb_printf(struct sbuf *s, const char *fmt, ...) __attribute__((format(printf, 2, 3)));
static void sb_printf(struct sbuf *s, const char *fmt, ...)
{
	va_list ap;
	int k;

	if (s->len >= s->n)
		return;
	va_start(ap, fmt);
	k = vsnprintf(s->b + s->len, s->n - s->len, fmt, ap);
	va_end(ap);
	if (k > 0)
		s->len += (size_t)k < s->n - s->len ? (size_t)k : s->n - s->len - 1;
}

int bench_plan_write(const char *path, const struct bench_plan *p)
{
	size_t size = 16384;
	char *buf = malloc(size);
	struct sbuf s = { buf, size, 0 };
	int r;

	if (!buf)
		return -ENOMEM;
	buf[0] = 0;
	sb_printf(&s, "; RetroStoneOS benchmark run (generated by the game process)\n");
	sb_printf(&s, "[bench]\nseconds = %d\nwarmup = %d\n\n[run]\n", p->seconds, p->warmup);
	sb_printf(&s, "game = \"%s\"\nsystem = \"%s\"\nrom_stem = \"%s\"\ncore_id = \"%s\"\n", p->game, p->system,
		  p->rom_stem, p->core_id);
	sb_printf(&s, "core_path = \"%s\"\nstate = \"%s\"\nstate_core = \"%s\"\n", p->core_path, p->state,
		  p->state_core);
	sb_printf(&s, "results = \"%s\"\nauto_state = \"%s\"\ndate = \"%s\"\n", p->results, p->auto_state, p->date);
	for (int i = 0; i < p->n; i++) {
		const struct bench_config *c = &p->c[i];

		sb_printf(&s, "\n[%s]\nlabel = \"%s\"\ncore = \"%s\"\n", c->id, c->label, c->core);
		for (int k = 0; k < c->nkv; k++)
			sb_printf(&s, "%s = \"%s\"\n", c->kv[k].key, c->kv[k].value);
	}
	r = hwrite_atomic(path, buf, s.len, false);
	free(buf);
	return r;
}

int bench_estimate_s(const struct bench_plan *p)
{
	/* ~8 s to start a GLES core and load a 16 MB state on the A20 */
	return p->n * (p->seconds + p->warmup + 8);
}

void bench_result_path(const char *plan_path, int i, char *out, size_t n)
{
	char dir[BENCH_PATH];

	hpath_dir(plan_path, dir, sizeof(dir));
	hpath(out, n, "%s/result-%d.ini", dir, i);
}

const struct bench_config *bench_find_config(const struct bench_plan *p, const char *id)
{
	for (int i = 0; i < p->n; i++)
		if (!strcmp(p->c[i].id, id))
			return &p->c[i];
	return NULL;
}

/* -------------------------------------------------------------- results */

int bench_result_format(const struct bench_result *r, char *buf, size_t n)
{
	return snprintf(buf, n,
			"id = \"%s\"\nlabel = \"%s\"\ncore = \"%s\"\nstatus = \"%s\"\nfrom_boot = %d\nblank = %d\n"
			"core_fps = %.4f\nsecs = %.3f\nspeed = %.2f\nfps = %.2f\neff_fps = %.2f\nvi = %.2f\n"
			"ft_avg = %.3f\nft_p95 = %.3f\nft_p99 = %.3f\ncore_ms = %.3f\nswap_ms = %.3f\n"
			"present_ms = %.3f\nreadback_ms = %.3f\nproc_cpu = %.1f\nncpu = %d\n"
			"cpu0 = %.1f\ncpu1 = %.1f\ncpu2 = %.1f\ncpu3 = %.1f\n"
			"runs = %llu\ndelivered = %llu\npresented = %llu\nskipped = %llu\ndupes = %llu\n"
			"shot = \"%s\"\nnote = \"%s\"\n",
			r->id, r->label, r->core, r->status, r->from_boot, r->blank, r->core_fps, r->secs, r->speed,
			r->fps, r->eff_fps, r->vi, r->ft_avg, r->ft_p95, r->ft_p99, r->core_ms, r->swap_ms,
			r->present_ms, r->readback_ms, r->proc_cpu, r->ncpu, r->cpu[0], r->cpu[1], r->cpu[2],
			r->cpu[3], r->runs, r->delivered, r->presented, r->skipped, r->dupes, r->shot, r->note);
}

int bench_result_parse(const char *text, struct bench_result *r)
{
	struct ini ini = { 0 };
	const char *v;

	memset(r, 0, sizeof(*r));
	if (ini_parse(&ini, text) < 0)
		return -EINVAL;
#define S(name) if ((v = ini_get(&ini, "", #name))) hstrlcpy(r->name, v, sizeof(r->name))
#define D(name) if ((v = ini_get(&ini, "", #name))) r->name = strtod(v, NULL)
#define U(name) if ((v = ini_get(&ini, "", #name))) r->name = strtoull(v, NULL, 10)
	S(id);
	S(label);
	S(core);
	S(status);
	S(shot);
	S(note);
	D(core_fps);
	D(secs);
	D(speed);
	D(fps);
	D(eff_fps);
	D(vi);
	D(ft_avg);
	D(ft_p95);
	D(ft_p99);
	D(core_ms);
	D(swap_ms);
	D(present_ms);
	D(readback_ms);
	D(proc_cpu);
	U(runs);
	U(delivered);
	U(presented);
	U(skipped);
	U(dupes);
#undef S
#undef D
#undef U
	r->from_boot = ini_get_bool(&ini, "", "from_boot", false);
	r->blank = ini_get_bool(&ini, "", "blank", false);
	r->ncpu = ini_get_int(&ini, "", "ncpu", 0);
	if (r->ncpu > 4)
		r->ncpu = 4;
	for (int i = 0; i < 4; i++) {
		char k[16];

		snprintf(k, sizeof(k), "cpu%d", i);
		if ((v = ini_get(&ini, "", k)))
			r->cpu[i] = strtod(v, NULL);
	}
	ini_free(&ini);
	return r->id[0] && r->status[0] ? 0 : -EINVAL;
}

int bench_result_load(const char *path, struct bench_result *r)
{
	size_t size;
	char *text = hread_file(path, &size);
	int ret;

	if (!text) {
		memset(r, 0, sizeof(*r));
		return -ENOENT;
	}
	ret = bench_result_parse(text, r);
	free(text);
	return ret;
}

bool bench_eligible(const struct bench_result *r)
{
	return !strcmp(r->status, "ok") && !r->from_boot && !r->blank && r->secs > 0 && r->runs > 0;
}

#define FULL_SPEED 98.0

/* <0: a ranks before b. */
static int rank_cmp(const struct bench_result *a, int ia, const struct bench_result *b, int ib)
{
	bool ea = bench_eligible(a), eb = bench_eligible(b);
	bool fa, fb;

	if (ea != eb)
		return ea ? -1 : 1;
	fa = a->speed >= FULL_SPEED;
	fb = b->speed >= FULL_SPEED;
	if (fa != fb)
		return fa ? -1 : 1;
	if (fa && a->eff_fps != b->eff_fps)
		return a->eff_fps > b->eff_fps ? -1 : 1;
	if (a->speed != b->speed)
		return a->speed > b->speed ? -1 : 1;
	return ia - ib;
}

int bench_rank(const struct bench_result *r, int n, int *order)
{
	for (int i = 0; i < n; i++)
		order[i] = i;
	for (int i = 1; i < n; i++) {
		int v = order[i], j = i - 1;

		while (j >= 0 && rank_cmp(&r[v], v, &r[order[j]], order[j]) < 0) {
			order[j + 1] = order[j];
			j--;
		}
		order[j + 1] = v;
	}
	return n > 0 && bench_eligible(&r[order[0]]) ? order[0] : -1;
}

static const char *row_note(const struct bench_result *r)
{
	if (strcmp(r->status, "ok"))
		return r->note[0] ? r->note : r->status;
	if (r->from_boot)
		return "from boot (other core cannot load the state): not ranked";
	if (r->blank)
		return "picture is one flat colour: broken renderer? not ranked";
	return r->note;
}

int bench_format_report(const struct bench_plan *p, const struct bench_result *r, int n, int best,
			bool finished, char *buf, size_t size)
{
	struct sbuf s = { buf, size, 0 };
	int order[BENCH_MAX_CONFIGS];

	if (!size)
		return 0;
	buf[0] = 0;
	sb_printf(&s, "RetroStoneOS benchmark\n");
	sb_printf(&s, "game: %s   system: %s   core at start: %s\n", p->game, p->system, p->core_id);
	sb_printf(&s, "date: %s   per configuration: %d s warm-up + %d s measured\n", p->date, p->warmup,
		  p->seconds);
	sb_printf(&s, "Every run restarts the game from the save state taken when the benchmark started (the\n"
		      "same scene), sends no input and runs unthrottled (no vsync, no audio pacing), so\n"
		      "speed can exceed 100 %%. speed = emulated VIs per second / the game's rate;\n"
		      "fps = new frames per second; eff.fps = frames the game shows at real speed;\n"
		      "p95/p99 = frame time that 5 %% / 1 %% of the frames exceed; swap = GPU blit +\n"
		      "eglSwapBuffers per frame; cpu = load of each CPU core.\n\n");
	sb_printf(&s, "%-3s %-12s %-30s %-6s %6s %6s %7s %6s %6s %6s %6s %7s %7s  %s\n", "#", "id", "settings",
		  "status", "speed%", "fps", "eff.fps", "p95ms", "p99ms", "coreMs", "swapMs", "cpu%", "skipped",
		  "note");
	for (int i = 0; i < n; i++) {
		const struct bench_result *x = &r[i];
		char cpu[24] = "-";

		if (x->ncpu >= 2)
			snprintf(cpu, sizeof(cpu), "%.0f/%.0f", x->cpu[0], x->cpu[1]);
		else if (x->ncpu == 1)
			snprintf(cpu, sizeof(cpu), "%.0f", x->cpu[0]);
		sb_printf(&s, "%-3d %-12.12s %-30.30s %-6.6s %6.1f %6.1f %7.1f %6.1f %6.1f %6.2f %6.2f %7s %7llu  %s\n",
			  i + 1, x->id, x->label, x->status, x->speed, x->fps, x->eff_fps, x->ft_p95, x->ft_p99,
			  x->core_ms, x->swap_ms, cpu, x->skipped, row_note(x));
	}
	if (!finished) {
		sb_printf(&s, "\n(running: %d of %d configurations done)\n", n, p->n);
		return (int)s.len;
	}
	bench_rank(r, n, order);
	sb_printf(&s, "\nRanking (full speed first, then the most frames shown; then the fastest):\n");
	for (int k = 0, shown = 0; k < n; k++) {
		const struct bench_result *x = &r[order[k]];

		if (!bench_eligible(x))
			continue;
		sb_printf(&s, "  %d. %-12s %-30s %5.1f %%  %5.1f eff.fps%s\n", ++shown, x->id, x->label, x->speed,
			  x->eff_fps, x->speed >= FULL_SPEED ? "  (full speed)" : "");
	}
	if (best >= 0) {
		const struct bench_config *c = bench_find_config(p, r[best].id);

		sb_printf(&s, "\nBest: %s (%s), core %s: %.1f %% speed, %.1f effective fps\n", r[best].id,
			  r[best].label, r[best].core, r[best].speed, r[best].eff_fps);
		if (c) {
			sb_printf(&s, "Settings (\"Use this for this game\" writes them to "
				      "/rsos/coreopts/%s/%s.ini):\n", c->core, p->game);
			for (int k = 0; k < c->nkv; k++)
				sb_printf(&s, "  %s = \"%s\"\n", c->kv[k].key, c->kv[k].value);
		}
		sb_printf(&s, "The benchmark measures speed only: check the screenshots before keeping a setting.\n");
	} else {
		sb_printf(&s, "\nNo configuration completed.\n");
	}
	return (int)s.len;
}

/* --------------------------------------------------------------- misc */

double bench_flat_fraction(const uint8_t *rgb, int w, int h)
{
	static uint32_t hist[4096];
	uint32_t max = 0;
	size_t n = (size_t)w * (size_t)h;

	if (!rgb || !n)
		return 1.0;
	memset(hist, 0, sizeof(hist));
	for (size_t i = 0; i < n; i++) {
		unsigned k = (unsigned)(rgb[3 * i] >> 4) << 8 | (unsigned)(rgb[3 * i + 1] >> 4) << 4 |
			     (unsigned)(rgb[3 * i + 2] >> 4);

		if (++hist[k] > max)
			max = hist[k];
	}
	return (double)max / (double)n;
}

int bench_filter_args(int argc, char *const *argv, bool for_step, const char **out, int max)
{
	static const char *const drop1[] = { "--load-state", "--load-state-file", "--bench-start",
					     "--bench-report", "--bench-driver" };
	static const char *const drop1_step[] = { "--status-fd", "--poweroff-cmd", "--dump", "--menu-shot" };
	int n = 0;

	for (int i = 0; i < argc; i++) {
		const char *a = argv[i];
		bool skip = false;

		if (!strcmp(a, "--bench-step")) {
			i += 2;
			continue;
		}
		for (size_t k = 0; k < sizeof(drop1) / sizeof(drop1[0]); k++)
			skip |= !strcmp(a, drop1[k]);
		for (size_t k = 0; for_step && k < sizeof(drop1_step) / sizeof(drop1_step[0]); k++)
			skip |= !strcmp(a, drop1_step[k]);
		if (skip) {
			i++;
			continue;
		}
		if (for_step && (!strcmp(a, "--test-states") || !strcmp(a, "--bench-auto-apply")))
			continue;
		if (n < max - 1)
			out[n++] = a;
	}
	out[n] = NULL;
	return n;
}

void bench_safe_name(const char *in, char *out, size_t n)
{
	size_t k = 0;
	bool us = false;

	if (!n)
		return;
	for (; *in && k + 1 < n; in++) {
		unsigned char ch = (unsigned char)*in;

		if ((ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || ch == '-') {
			out[k++] = (char)ch;
			us = false;
		} else if (!us && k > 0) {
			out[k++] = '_';
			us = true;
		}
	}
	while (k > 0 && out[k - 1] == '_')
		k--;
	out[k] = 0;
	if (!k)
		hstrlcpy(out, "game", n);
}

/* ------------------------------------------------------- writing files */

int bench_write_keys(const char *path, const char *header, const struct bench_kv *kv, int n)
{
	struct ini old = { 0 };
	struct sbuf s;
	char *buf;
	size_t size = 8192;
	int r;

	/* never rewrite a file we could not read (only "no file yet" is empty) */
	r = ini_load(&old, path);
	if (r < 0 && r != -ENOENT) {
		hlog(HLOG_ERROR, "%s: cannot read (%s): not rewritten", path, strerror(-r));
		ini_free(&old);
		return r;
	}
	for (int i = 0; i < old.n; i++)
		size += strlen(old.e[i].key) + strlen(old.e[i].value) + 8;
	buf = malloc(size);
	if (!buf) {
		ini_free(&old);
		return -ENOMEM;
	}
	s = (struct sbuf){ buf, size, 0 };
	buf[0] = 0;
	sb_printf(&s, "%s\n", header ? header : "; RetroStoneOS core options");
	for (int i = 0; i < old.n; i++) {
		bool replaced = false;

		for (int k = 0; k < n; k++)
			replaced |= !strcasecmp(old.e[i].key, kv[k].key);
		if (!replaced)
			sb_printf(&s, "%s = \"%s\"\n", old.e[i].key, old.e[i].value);
	}
	for (int k = 0; k < n; k++)
		sb_printf(&s, "%s = \"%s\"\n", kv[k].key, kv[k].value);
	ini_free(&old);
	r = hwrite_atomic(path, buf, s.len, false);
	free(buf);
	return r;
}

int bench_ini_set_file(const char *path, const char *section, const char *key, const char *value)
{
	struct ini ini = { 0 };
	const char **secs;
	int nsec = 0, r;
	size_t size = 4096;
	char *buf;
	struct sbuf s;

	/* Review F-M9: a read error used to rewrite cores.ini with only the
	 * new key, and sections past the 64th were dropped. */
	r = ini_load(&ini, path);
	if (r < 0 && r != -ENOENT) {
		hlog(HLOG_ERROR, "%s: cannot read (%s): not rewritten", path, strerror(-r));
		ini_free(&ini);
		return r;
	}
	if (ini_set(&ini, section, key, value) < 0) {
		ini_free(&ini);
		return -ENOMEM;
	}
	secs = malloc(sizeof(*secs) * (size_t)(ini.n + 1));
	if (!secs) {
		ini_free(&ini);
		return -ENOMEM;
	}
	for (int i = 0; i < ini.n; i++) {
		bool seen = false;

		size += strlen(ini.e[i].section) + strlen(ini.e[i].key) + strlen(ini.e[i].value) + 16;
		for (int k = 0; k < nsec && !seen; k++)
			seen = !strcmp(secs[k], ini.e[i].section);
		if (!seen)
			secs[nsec++] = ini.e[i].section;
	}
	buf = malloc(size);
	if (!buf) {
		free(secs);
		ini_free(&ini);
		return -ENOMEM;
	}
	s = (struct sbuf){ buf, size, 0 };
	buf[0] = 0;
	/* the top-level keys first, then each section in order */
	for (int pass = 0; pass < 2; pass++)
		for (int k = 0; k < nsec; k++) {
			if ((pass == 0) != (secs[k][0] == 0))
				continue;
			if (secs[k][0])
				sb_printf(&s, "%s[%s]\n", s.len ? "\n" : "", secs[k]);
			for (int i = 0; i < ini.n; i++)
				if (!strcmp(ini.e[i].section, secs[k]))
					sb_printf(&s, "%s = \"%s\"\n", ini.e[i].key, ini.e[i].value);
		}
	r = hwrite_atomic(path, buf, s.len, true);   /* cores.ini.bak: coreinfo_pick() fallback */
	free(buf);
	free(secs);
	ini_free(&ini);
	return r;
}

int bench_apply(const struct bench_config *c, const char *user_dir, const char *game,
		const char *choices_path, const char *system, const char *rom_stem,
		const char *current_core)
{
	char path[BENCH_PATH], dir[BENCH_PATH], hdr[200];
	int r;

	if (!hpath(dir, sizeof(dir), "%s/%s", user_dir, c->core) ||
	    !hpath(path, sizeof(path), "%s/%s.ini", dir, game))
		return -ENAMETOOLONG;
	hmkdir_p(dir, 0755);
	snprintf(hdr, sizeof(hdr), "; RetroStoneOS core options (%s), benchmark choice \"%s\"", c->core, c->id);
	r = bench_write_keys(path, hdr, c->kv, c->nkv);
	if (r)
		return r;
	if (choices_path && current_core && strcmp(c->core, current_core) != 0) {
		char sec[512];

		if (!hpath(sec, sizeof(sec), "%s/%s", system, rom_stem))
			return -ENAMETOOLONG;
		r = bench_ini_set_file(choices_path, sec, "core", c->core);
	}
	return r;
}
